CREATE TABLE IF NOT EXISTS `new_agents` (
  `AGENT_CODE` varchar(6) NOT NULL DEFAULT '',
  `AGENT_NAME` varchar(40) DEFAULT NULL,
  `WORKING_AREA` varchar(35) DEFAULT NULL,
  `COMMISSION` decimal(10,2) DEFAULT NULL,
  `PHONE_NO` varchar(15) DEFAULT NULL,
  `COUNTRY` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`AGENT_CODE`)
) 

INSERT INTO new_agents (AGENT_NAME, WORKING_AREA, COMMISSION, PHONE_NO, COUNTRY )
SELECT AGENT_NAME,　WORKING_AREA, COMMISSION, PHONE_NO, COUNTRY FROM agents
WHERE agents.WORKING_AREA = 'London';

UPDATE new_agents
SET new_agents.COUNTRY = 'UK'
WHERE new_agents.AGENT_CODE IN 
(
    SELECT customer.AGENT_CODE
    FROM customer
    WHERE customer.CUST_COUNTRY = 'UK'
);